api-server/config/routes.rb
JArchive::Application.routes.draw do

  get "search" => "search#index"
  get "search/:query" => "search#index", :as => "search_term"

  get "popular" => "popular#index"
  get "popular/:category_id" => "popular#list", :as => "popular_list"
  get "api/random" => "api#random",  defaults: {format: :json}
  get "api/clues" => "api#clues", defaults: {format: :json}
  get "api/categories" => "api#categories", defaults: {format: :json}
  get "api/category" => "api#single_category", defaults: {format: :json}
  get "api/rando_clues" => "api#rando_set", defaults: {format: :json}
  post "api/invalid" => "api#mark_invalid", defaults: {format: :json}

  get "index/home", :as => "home"
  get "index/about"
  resources :game_ids

  resources :categories

  resources :clues

  root :to => 'index#home'

end

api-server/app/controllers/game_ids_controller.rb
class GameIdsController < ApplicationController
  before_action :set_game_id, only: [:show, :edit, :update, :destroy]

  # GET /game_ids
  def index
    @game_ids = GameId.all
  end

  # GET /game_ids/1
  def show
  end

  # GET /game_ids/new
  def new
    @game_id = GameId.new
  end

  # GET /game_ids/1/edit
  def edit
  end

  # POST /game_ids
  def create
    @game_id = GameId.new(game_id_params)

    if @game_id.save
      redirect_to @game_id, notice: 'Game was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /game_ids/1
  def update
    if @game_id.update(game_id_params)
      redirect_to @game_id, notice: 'Game was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /game_ids/1
  def destroy
    @game_id.destroy
    redirect_to game_ids_url, notice: 'Game was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_id
      @game_id = GameId.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_id_params
      params.require(:game_id).permit(:id)
    end
end

api-server/app/helpers/game_ids_helper.rb
module GameIdsHelper
end

api-server/app/views/game_ids/_form.html.erb
<%= form_for(@game_id) do |f| %>
  <% if @game_id.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_id.errors.count, "error") %> prohibited this game_id from being saved:</h2>

      <ul>
      <% @game_id.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

api-server/app/views/game_ids/edit.html.erb
<h1>Editing game_id</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_id %> |
<%= link_to 'Back', game_ids_path %>

api-server/app/views/game_ids/index.html.erb
<h1>Listing game_ids</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @game_ids.each do |game_id| %>
      <tr>
        <td><%= game_id.id %></td>
        <td><%= link_to 'Show', game_id %></td>
        <td><%= link_to 'Edit', edit_game_id_path(game_id) %></td>
        <td><%= link_to 'Destroy', game_id, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_id_path %>

api-server/app/views/game_ids/new.html.erb
<h1>New game_id</h1>

<%= render 'form' %>

<%= link_to 'Back', game_ids_path %>

api-server/app/views/game_ids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @game_id.id %>
</p>

<%= link_to 'Edit', edit_game_id_path(@game_id) %> |
<%= link_to 'Back', game_ids_path %>