api-server/config/routes.rb
JArchive::Application.routes.draw do

  get "search" => "search#index"
  get "search/:query" => "search#index", :as => "search_term"

  get "popular" => "popular#index"
  get "popular/:category_id" => "popular#list", :as => "popular_list"
  get "api/random" => "api#random",  defaults: {format: :json}
  get "api/clues" => "api#clues", defaults: {format: :json}
  get "api/categories" => "api#categories", defaults: {format: :json}
  get "api/category" => "api#single_category", defaults: {format: :json}
  get "api/rando_clues" => "api#rando_set", defaults: {format: :json}
  post "api/invalid" => "api#mark_invalid", defaults: {format: :json}

  get "index/home", :as => "home"
  get "index/about"
  resources :game_ids

  resources :categories

  resources :clues

  root :to => 'index#home'

end

api-server/app/controllers/popular_controller.rb
class PopularController < ApplicationController
  def index
  	#@list = Category.includes(:clues).limit(100)
  	@list = Category.where("clues_count > 100").order("clues_count DESC")
  end
  def list
  	@category = Category.find(params[:category_id])
  	@list = Clue.where("category_id = ? AND question != ''", params[:category_id]).order("airdate DESC, value ASC")
  end
end

api-server/app/helpers/popular_helper.rb
module PopularHelper
end

api-server/app/views/popular/index.html.erb
<%= render "layouts/menu" %>

<ol class="breadcrumb">
  <li><%= link_to "Popular Categories" %></li>
</ol>

<div class="container">
<h3>Popular Categories</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Category</th>
      <th>Clue Count</th>
    </tr>
  </thead>
  <tbody>
    <% @list.each do |cat| %>
      <tr>
        <td><%= link_to cat.title.titleize, popular_list_path(cat.id) %></td>
        <td><%= cat.clues_count %></td>

              </tr>
    <% end %>
  </tbody>
</table>
</div>

api-server/app/views/popular/list.html.erb
<%= render "layouts/menu" %>
<%- model_class = Clue -%>
<ol class="breadcrumb">
  <li><%= link_to "Popular Categories", popular_path %></li>
  <li><%= link_to @category.title.titleize %></li>
</ol>

<div class="container">
<h3>Clues for: <%= @category.title.titleize %></h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:answer) %></th>

      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:airdate) %></th>

    </tr>
  </thead>
  <tbody>
    <% @list.each do |clue| %>
      <tr>
        <td><%= clue.question %></td>
        <td><%= clue.answer %></td>

        <td><%= clue.value %></td>
        <td><%= clue.airdate.to_time.strftime('%B %e, %Y') %></td>
              </tr>
    <% end %>
  </tbody>
</table>
</div>