api-server/config/routes.rb
JArchive::Application.routes.draw do

  get "search" => "search#index"
  get "search/:query" => "search#index", :as => "search_term"

  get "popular" => "popular#index"
  get "popular/:category_id" => "popular#list", :as => "popular_list"
  get "api/random" => "api#random",  defaults: {format: :json}
  get "api/clues" => "api#clues", defaults: {format: :json}
  get "api/categories" => "api#categories", defaults: {format: :json}
  get "api/category" => "api#single_category", defaults: {format: :json}
  get "api/rando_clues" => "api#rando_set", defaults: {format: :json}
  post "api/invalid" => "api#mark_invalid", defaults: {format: :json}

  get "index/home", :as => "home"
  get "index/about"
  resources :game_ids

  resources :categories

  resources :clues

  root :to => 'index#home'

end

api-server/app/views/index/about.html.erb
<h1>Index#about</h1>
<p>Find me in app/views/index/about.html.erb</p>

api-server/app/views/index/home.html.erb
<% content_for :title do %>
    jService - Over <%= number_with_delimiter(@count.round(-2)) %> trivia questions
<% end %>


<div class="bs-header">
	<div class="container">
		<div class="col-md-6">
			<%= image_tag ("trebek.png") %>
		</div>
		<div class="col-md-6">
			<h1>jService</h1>
			<h2><%= number_with_delimiter(@count.round(-2)) %> Trivia Questions</h2>
			<p>A set of trivia services by <a href="http://github.com/sottenad">@sottenad</a></p>
			<p><a href="https://github.com/sottenad/jService" class="btn btn-primary btn-large">View On Github</a></p>
		</div>
	</div>
</div>

<div class="container">
	<div class="col-md-7">
		<h3>API Usage</h3>
		<h4>/Clues</h4>
		<ul>
			<li>Url: <code>/api/clues</code></li>
			<li>Options <small class="text-warning">All options are optional</small>:
				<ul>
					<li><code>value</code>(int): the value of the clue in dollars</li>
					<li><code>category</code>(int): the id of the category you want to return</li>
					<li><code>min_date</code>(date): earliest date to show, based on original air date</li>
					<li><code>max_date</code>(date): latest date to show, based on original air date</li>
					<li><code>offset</code>(int): offsets the returned clues. Useful in pagination</li>
				</ul>
		</ul> 
		<h4>/Random</h4>
		<ul>
			<li>Url: <code>/api/random</code></li>
			<li>Options:
				<ul>
					<li><code>count</code>(int): amount of clues to return, limited to 100 at a time</li>
				</ul>
		</ul>
		<h4>/Categories</h4>
		<ul>
			<li>Url: <code>/api/categories</code></li>
			<li>Options:
				<ul>
					<li><code>count</code>(int): amount of categories to return, limited to 100 at a time</li>
					<li><code>offset</code>(int): offsets the starting id of categories returned. Useful in pagination.</li>
				</ul>
		</ul>
		<h4>/Category</h4>
		<ul>
			<li>Url: <code>/api/category</code></li>
			<li>Options:
				<ul>
					<li><code>id</code>(int): <span class="text-warning">Required</span> the ID of the category to return.</li>
				</ul>
		</ul>
        <h4>/Invalid</h4>
		<ul>
			<li>Url: <code>/api/invalid</code></li>
			<li>Options:
				<ul>
					<li><code>id</code>(int): <span class="text-warning">Required</span> the ID of the clue to mark as invalid. <br />
                                <p>Please mark a clue as invalid when the needed information is not present in the clue. This sometimes happens when clues rely on images or sounds to be answered. When useing jService, you may want to check the invalid_count attribute on clues before using them.</p>
                    </li>
				</ul>
        
		</ul>
		<hr />
		<h3>Popular</h3>
		<p>Jeopardy&reg; is constantly adding more clues to some of the same popular categories. The categories/clues are stored relationally so we can view the most popular categories, or view all clues associated with a particular category, given its id.</p>
		<p>
            <%= link_to "View Popular Categories", popular_path, :class => 'btn btn-default' %>
            <%= link_to "Search Categories", search_path, :class => 'btn btn-default' %>
        </p>
		<hr />
		<h3>About</h3>
		<p>This is in large part a project to learn a bit about screen-scraping and creating an easily consumable set of services for public consumption. I will be offering this free of charge, but on a small Heroku instance until sufficient demand exists. Production use is at your own risk.</p>
		
		
		
		
	</div>
	<div class="col-md-5">
		<div class="panel panel-default" id="quiz-question">
			<div class="panel-heading">
				<h4>Random Question<span class="glyphicon glyphicon-refresh" id='refresh-question'></span></h4>
				
			</div>
			<div class="panel-body">

			</div>
		</div>
	</div>	
</div>

<script id="quiz-template" type="text/x-handlebars-template">
	<table class="table table-hover table-bordered">
		<tr>
			<td><strong>Difficulty</strong></td>
			<td>{{value}}</td>
		</tr>
		<tr>
			<td><strong>Category</strong></td>
			<td>{{{category.title}}}</td>
		</tr>
		<tr>
			<td><strong>Question</strong></td>
			<td>{{{question}}}</td>
		</tr>
		<tr>
			<td><strong>Answer</strong></td>
			<td>{{{answer}}}</td>
		</tr>
		<tr>
			<td><strong>Air Date</strong></td>
			<td>{{clean_time airdate}}</td>
		</tr>
        <tr>
			<td><strong>ID</strong></td>
			<td id="clue-id">{{id}}</td>
		</tr>
		<tr>
			<td><strong>Invalid Count <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="top" title="Sometimes clues rely on images or sounds, mark as invalid to help clean the DB"></span></strong></td>
			<td>
                <div class="row">
                    <div class="col-sm-6">
                        <span id="invalid-count">
                        {{#if invalid_count}}
                            {{invalid_count}}
                        {{else}}
                            0
                        {{/if}}
                        </span>
                    </div>
                    <div class="col-sm-6">
                        <small><a href="#" class="pull-right" id="mark-invalid">Mark Invalid</a></small>
                    </div>
            </td>
		</tr>

	</table>
	<h5 class="left">Raw Response</h5>
	<div class="raw">
		<pre>{{json .}}</pre>
	</div>
</script>